[build]
  publish = "public"
  command = "yarn build # && yarn verify-sitemap ${URL} ${DEPLOY_URL}"
  
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/bigtest*"
  to = "https://bigtest.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://frontside.io/*"
  to = "https://frontside.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.frontside.io/*"
  to = "https://frontside.com/:splat"
  status = 301
  force = true